feat(submissions): add Plugin Submissions page
Vencord/Docs pull request #4
Opened 2024-07-09 07:57 UTC by Bluejutzu

2024-07-12 07:07 UTC, Bluejutzu commented
sidebar currently 
![sidebar](https://github.com/user-attachments/assets/c5eb2562-c12d-47ff-818a-3c6723a6c7fe)

2024-07-13 10:05 UTC, Faf4a requested changes

2024-07-13 10:05 UTC, Faf4a commented on src/content/docs/contribute.md
> +Vencord provides plugins to modify the Discord Client to your liking. If you want to create your own plugin head to [Plugin Development](http://localhost:4321/installing/)
```suggestion
Vencord provides plugins to modify the Discord Client to your liking. If you want to create your own plugin head to [Plugin Development](/installing/)
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/plugins/submission.md
> +After creating the PR your code will go through checks and needs to get approved before getting pushed into the `main` (or `dev`) build of Vencord.
PRs aren't merged to main

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/plugins/submission.md
> +However, if your PR get's denied don't worry. Vencords Maintainers give comments on approval/denial, so you can always fix any issues. Unless your plugin is in violation of rules.
```suggestion
However, if your PR gets denied, don't worry. Vencords Maintainers give comments on approval/denial, so you can always fix any issues. Unless your plugin is in violation of rules.
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/advanced/utils/datastore.mdx
> +This should always be preferred over the Settings API if possible, as localstorage has very strict size restrictions and blocks the event loop and make sure your keys are unique (tip: prefix them wit
```suggestion
This should always be preferred over the Settings API if possible, as localstorage has very strict size restrictions and blocks the event loop. Make sure your keys are unique (tip: prefix them with your plugin name) and please clean up no longer needed entries.
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/advanced/plugins/optionComponent.mdx
> +Now to the `component`. You can either build a component directly in it or import it from another file. In this guide we create the component in another file and import it later on.
```suggestion
Now to the `component`. You can either build a component directly in it or import it from another file. In this guide we will create the component in another file and import it later on.
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/advanced/plugins/optionComponent.mdx
> +Now build your code with `pnpm build` (or `pnpm watch`) and then inject it `pnpm inject`.
You don't need to run inject on every build

```suggestion
Now build your code with `pnpm build` (or `pnpm watch`).
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/advanced/utils/datastore.mdx
> +First import it from `@api/index` (alias `src/api/DataStore/index`).
```suggestion
First import it from `@api/index` (alias for `src/api/DataStore/index`).
```

2024-07-13 11:50 UTC, schoeneBiene commented on src/content/docs/contribute.md
> +Vencord provides plugins to modify the Discord Client to your liking. If you want to create your own plugin head to [Plugin Development](/installing/)
```suggestion
Vencord provides plugins to modify the Discord Client to your liking. If you want to create your own plugins, head to [Plugin Development](/installing/)
```

2024-07-13 12:02 UTC, Bluejutzu commented on src/content/docs/plugins/submission.md
> +After creating the PR your code will go through checks and needs to get approved before getting pushed into the `main` (or `dev`) build of Vencord.
alright 👍

2024-08-29 05:45 UTC, Bluejutzu commented
Ready for review

2024-08-29 14:39 UTC, taskylizard commented on src/content/docs/additional/cloud.md
> +description: Vencords own API
Could do a better description perhaps?

2024-08-29 14:43 UTC, taskylizard commented on src/content/docs/additional/cloud.md
> +Copy the example configuration (`.env.example`) to `.env`. Now open it with your text editor of trust and fill in the configuration values.
"text editor of trust" sounds weird, can be "text editor of choice"

2024-08-29 14:44 UTC, taskylizard commented on src/content/docs/additional/cloud.md
> +We provide a Docker build, so you don't need anything installed besides Docker!
Should have link to installing docker compose: https://docs.docker.com/compose/install/

2024-08-29 15:01 UTC, Bluejutzu commented on src/content/docs/additional/cloud.md
> +description: Vencords own API
Done

2024-11-15 11:53 UTC, closed without merging